### ISSUE TITLE
Search: This would have to come at the end when we have more content, but think we should have something related to this.

### ISSUE THREAD

**Issue by abquirarte** [cagov/Alpha#248] opened 2020-01-23 16:32 UTC
** @lukefretwell suggestion** 

_Search: This would have to come at the end when we have more content, but think we should have something related to this._

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lukefretwell** [comment] 2020-01-23 19:30
Closing this as it's a dupe of https://github.com/cagov/Alpha/issues/201.

**Closed by lukefretwell** 2020-01-23 19:30 UTC
Labels: enhancement
